name: Test Install Vault CLI Action

on:
  push:

jobs:
  test-action:
    name: Test Install Vault CLI Action
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - package_manager: npm
            vault_cli_version: 0.47.0
            with_sudo: true
          - package_manager: yarn
            vault_cli_version: 0.45.0
            with_sudo: true
    steps:
      - name: Install Vault-CLI
        uses: LedgerHQ/vault-cli-setup@v3
        with:
          package_manager: ${{ matrix.package_manager }}
          vault_cli_version: ${{ matrix.vault_cli_version }}
          with_sudo: ${{ matrix.with_sudo }}

      - name: Check Version
        run: ledger-vault -v
